server:
  port: 8080

spring:
  application:
    name: api-gateway
    
  cloud:
    gateway:
      routes:
      - id: bodegas-service
        uri: lb://BODEGAS-SERVICE
        predicates:
        - Path=/productos/**
      - id: ventas-service
        uri: lb://VENTAS-SERVICE
        predicates:
        - Path=/ventasdetalle/**
      
      
eureka:
  instance:    
    preferIpAddress: true
  client: 
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:9999/eureka    
  