spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ecosistema
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  boot:
    admin:
      client:
        url: http://localhost:7777
server:
  port: 8089
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9999/eureka
      
      
management:
  endpoints:
    web:
      exposure:
        include: '*'
    jmx:
      exposure:
        include: '*'
  endpoint:
    health:
      enabled: true

  
      