spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ecosistema
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8088
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9999/eureka