
server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
      - id: productos
        uri: lb://PRODUCTOS-SERVICE
        predicates:
        - Path=/productos/**
        filters:
        - AuthFilter
      - id: ventas
        uri: lb://VENTAS-SERVICE
        predicates:
        - Path=/ventas/**
        filters:
        - AuthFilter
      - id: login
        uri: lb://LOGIN-SERVICE
        predicates:
        - Path=/login/loggeo,/login/validateToken

eureka:
  instance:
    preferIpAddress: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:9999/eureka   