
server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
      - id: productos
        uri: lb://PRODUCTOS-SERVICE
        predicates:
        - Path=/productos/**
      - id: ventas
        uri: lb://VENTAS-SERVICE
        predicates:
        - Path=/ventas/**

eureka:
  instance:
    preferIpAddress: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:9999/eureka   