
server:
  port: 8080
  ssl:
    key-store-password: 123456789
    key-store-type: PKCS12
    key-store: classpath:myfile.p12
    enabled: true
    key-alias: ecosistema
    
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
      - id: productos
        uri: lb://PRODUCTOS-SERVICE
        predicates:
        - Path=/productos/**
        filters:
        - AuthFilter
      - id: ventas
        uri: lb://VENTAS-SERVICE
        predicates:
        - Path=/ventas/**
        filters:
        - AuthFilter
      - id: login
        uri: lb://LOGIN-SERVICE
        predicates:
        - Path=/login/loggeo,/login/validateToken

eureka:
  instance:
    preferIpAddress: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:9999/eureka   
      

  